<script setup lang="ts">
import { MARK_EYES, MARK_BLOOM, WORDMARK, LOCKUP } from '../brand-art';

/**
 * Indahnya's mark, Mekar: three corners of a QR code, and where the fourth
 * should be, a flower. The wordmark is "indahnya" in Bricolage Grotesque,
 * outlined (no font to load), its i dotted with a kerawang flower.
 * Generated by scripts/build-brand.py; brand/ holds the files and rules.
 *
 * Ink follows `currentColor` (set a text colour to put it on dark), the
 * flowers stay brand green unless `mono`. `size` is the mark's height in
 * px; the wordmark is drawn to match. `inherit` takes the parent's colour
 * instead of ink (the kad badge, in each template's own muted ink).
 */
const props = withDefaults(defineProps<{ size?: number; wordmark?: boolean; mono?: boolean; inherit?: boolean }>(), { size: 28, wordmark: true, mono: false, inherit: false });
const green = computed(() => (props.mono ? 'currentColor' : '#7dd56f'));
const flower = computed(() => WORDMARK.flowerSvg.replaceAll('{P}', green.value));
const width = computed(() => (props.wordmark ? Math.round(props.size * LOCKUP.perMark / LOCKUP.ratio) : props.size));
const height = computed(() => (props.wordmark ? Math.round(props.size * LOCKUP.perMark) : props.size));
</script>

<template>
  <svg
    class="logo inline-block shrink-0 select-none align-middle" :class="!inherit && 'text-ink-900'" :width="width" :height="height"
    :viewBox="wordmark ? LOCKUP.viewBox : '0 0 64 64'" role="img" aria-label="Indahnya"
  >
    <g :transform="wordmark ? LOCKUP.markTransform : undefined">
      <path fill-rule="evenodd" fill="currentColor" :d="MARK_EYES" />
      <circle v-for="[x, y] in MARK_BLOOM" :key="`${x}${y}`" :cx="x" :cy="y" r="6.4" :fill="green" />
      <circle v-if="!mono" cx="47" cy="47" r="3.1" fill="currentColor" />
    </g>
    <g v-if="wordmark" :transform="`translate(${LOCKUP.wordX} 0)`">
      <path :d="WORDMARK.path" fill="currentColor" />
      <g v-html="flower" />
    </g>
  </svg>
</template>
