/**
 * Landing copy, both languages, in one place. BM is the default and is
 * written the way people talk at a majlis; EN is for the SG/expat couple
 * and the venue manager. Keys are grouped by section.
 */
export const LANDING = {
  ms: {
    nav: { how: 'Cara guna', features: 'Ciri', pricing: 'Harga', faq: 'Soalan', login: 'Log masuk', cta: 'Buat majlis percuma', lang: 'EN' },
    hero: {
      eyebrow: 'Untuk majlis kahwin, aqiqah, birthday & majlis syarikat',
      h1a: 'Semua gambar majlis.',
      h1b: 'Dari semua phone.',
      h1c: 'Satu QR.',
      sub: 'Tetamu scan, upload terus. Tak payah download app, tak payah login. Gambar naik live ke TV dewan, dan korang dapat semua dalam satu galeri.',
      cta: 'Buat majlis — percuma',
      demo: 'Tengok galeri contoh',
      trust: 'Bayar sekali dari RM59. Tak ada subscription.',
      live: 'LIVE',
      photos: 'gambar',
    },
    how: {
      eyebrow: 'Cara guna',
      title: 'Tiga langkah. Tak payah ajar makcik.',
      steps: [
        { n: '01', title: 'Letak QR atas meja', body: 'Print template A5 atau kad meja kami, letak kat setiap meja tetamu dan pintu masuk.' },
        { n: '02', title: 'Tetamu scan & upload', body: 'Buka terus dalam browser phone. Pilih gambar dari galeri atau snap terus — 30 gambar sekali gus.' },
        { n: '03', title: 'Naik live ke TV', body: 'Setiap gambar muncul dalam galeri dan atas skrin dewan dalam beberapa saat, dengan nama siapa yang snap.' },
      ],
      phone: { title: 'Upload gambar', sub: 'Pilih dari galeri phone atau snap terus', uploading: 'Tengah upload…', done: 'Siap! 12 gambar dah masuk galeri' },
      tv: { scan: 'Scan untuk upload' },
    },
    features: {
      eyebrow: 'Ciri',
      title: 'Semua yang Wedibox ada. Dalam Ringgit, dalam BM.',
      items: [
        { title: 'Galeri live', body: 'Gambar & video tetamu masuk serta-merta. Kualiti asal disimpan, HEIC iPhone ditukar sendiri.' },
        { title: 'Slideshow TV', body: 'Satu link untuk laptop dewan. Gambar baru menyelit masuk rotation, nama tetamu sekali.' },
        { title: 'Kad jemputan digital', body: 'Dua pihak, aturcara, Waze & Google Maps, countdown, salam kaut DuitNow. Satu link untuk semua.' },
        { title: 'RSVP & tempat duduk', body: 'Tetamu confirm kehadiran dan pax, korang susun meja, tetamu cari nombor meja sendiri.' },
        { title: 'Ucapan tulis & suara', body: 'Tetamu tinggalkan ucapan atau rakam suara terus dari browser. Tak payah sewa telefon vintage.' },
        { title: 'Download semua', body: 'Satu zip, kualiti asal, susun ikut masa. Gambar yang korang sembunyikan pun ada, dalam folder sendiri.' },
        { title: 'Kawalan tuan majlis', body: 'Sembunyi, padam, atau approval mode — gambar hanya naik selepas korang tengok dulu.' },
        { title: 'Link sendiri', body: 'indahnya.my/aina-hakim. Pendek, senang sebut, senang print.' },
      ],
    },
    host: {
      eyebrow: 'Untuk tuan majlis',
      title: 'Dashboard yang korang boleh buka masa tengah bersanding.',
      body: 'Semua dari phone: berapa gambar dah masuk, siapa dah RSVP, sembunyi gambar yang tak sesuai, copy link TV. Tak ada yang tersorok tiga menu dalam.',
      stats: [
        { label: 'Gambar & video', value: '318', sub: 'dalam galeri' },
        { label: 'Upload digunakan', value: '318', sub: 'tanpa had' },
        { label: 'RSVP', value: '142', sub: '· 380 pax' },
        { label: 'Ucapan', value: '27', sub: 'dari tetamu' },
      ],
      recent: 'Gambar terkini',
      recentSub: 'Yang baru masuk dari tetamu',
      plan: 'Pakej',
      planName: 'Indahnya Lengkap',
      planLine1: 'Upload terbuka 341 hari lagi',
      planLine2: 'Simpanan sampai 14 November 2028',
      actions: 'Buat sekarang',
      a1: 'Print QR untuk meja', a1s: 'A5, A4 atau kad meja',
      a2: 'Pasang slideshow kat TV', a2s: 'Gambar masuk live masa majlis',
      a3: 'Download semua (zip)', a3s: '318 fail, kualiti asal',
    },
    print: {
      eyebrow: 'Untuk meja',
      title: 'Template print, siap dengan QR dan nama korang.',
      body: 'Buka, tekan Print. A5 untuk bingkai meja, A4 untuk stand pintu masuk, kad meja lipat dua. Dalam BM atau English ikut tetamu.',
      items: ['Poster A5', 'Poster A4', 'Kad meja'],
      headline: 'Snap & share gambar majlis kami',
    },
    pricing: {
      eyebrow: 'Harga',
      title: 'Bayar sekali. Untuk satu majlis.',
      body: 'Tak ada subscription, tak ada per-tetamu. Mula percuma dengan semua ciri, upgrade bila galeri dah penuh.',
      plans: [
        { name: 'Percuma', price: 'RM0', tag: 'Untuk cuba', rows: ['50 upload', 'Upload 30 hari', 'Simpan 30 hari', 'Semua ciri, termasuk slideshow & kad'], cta: 'Mula percuma', hot: false },
        { name: 'Indahnya', price: 'RM59', tag: 'Paling ramai pilih', rows: ['Upload tanpa had', 'Upload 6 bulan', 'Simpan 1 tahun', 'Link sendiri', '1 co-host'], cta: 'Pilih Indahnya', hot: true },
        { name: 'Indahnya Lengkap', price: 'RM99', tag: 'Untuk majlis besar', rows: ['Upload tanpa had', 'Upload 12 bulan', 'Simpan 2 tahun', 'Link sendiri', '5 co-host', 'Tanpa badge Indahnya'], cta: 'Pilih Lengkap', hot: false },
      ],
      note: 'Bayaran melalui Stripe — FPX, kad, GrabPay. Harga dalam Ringgit. Resit ke email.',
    },
    faq: {
      eyebrow: 'Soalan',
      title: 'Yang orang selalu tanya.',
      items: [
        { q: 'Tetamu kena download app ke?', a: 'Tak. Scan QR, browser phone terus buka galeri. iPhone, Android, phone lama makcik — semua jalan.' },
        { q: 'Kalau tetamu tak ada internet kat dewan?', a: 'Gambar yang tak sempat upload akan cuba lagi bila ada line. Untuk TV, guna hotspot phone — slideshow tetap jalan dengan gambar yang dah ada.' },
        { q: 'Boleh tapis gambar yang tak sesuai?', a: 'Boleh. Sembunyi atau padam dari dashboard, atau on approval mode supaya gambar hanya naik selepas korang tengok.' },
        { q: 'Gambar disimpan berapa lama?', a: 'Percuma: 30 hari. RM59: setahun. RM99: dua tahun. Kami email 14 hari sebelum tamat, dan korang boleh download semua bila-bila.' },
        { q: 'Video boleh?', a: 'Boleh, sampai 60 saat setiap satu. Kami tukar ke format yang main kat semua phone, jadi video iPhone pun boleh tengok kat Android.' },
        { q: 'Kad jemputan dah buat kat tempat lain, boleh guna galeri je?', a: 'Boleh. Ada QR dan link "Gambar sahaja" yang terus masuk galeri — paste dalam e-kad korang.' },
        { q: 'Siapa yang buat Indahnya?', a: 'FF Dev Studio, studio kecil di Malaysia. Kalau ada masalah, WhatsApp kami — orang yang bina benda ni yang jawab.' },
      ],
    },
    cta: { title: 'Buat majlis korang dalam dua minit.', body: 'Percuma untuk mula. QR siap sebelum korang habis baca ayat ni.', button: 'Buat majlis percuma' },
    footer: { by: 'Dibuat oleh', tagline: 'Galeri gambar majlis dengan QR, untuk Malaysia.', links: { privacy: 'Privasi', terms: 'Terma', contact: 'Hubungi' } },
  },
  en: {
    nav: { how: 'How it works', features: 'Features', pricing: 'Pricing', faq: 'FAQ', login: 'Sign in', cta: 'Create an event free', lang: 'BM' },
    hero: {
      eyebrow: 'For weddings, aqiqah, birthdays & company events',
      h1a: 'Every photo from the event.',
      h1b: 'From every phone.',
      h1c: 'One QR.',
      sub: 'Guests scan and upload right away. No app, no sign-up. Photos go live on the venue screen, and you get all of them in one gallery.',
      cta: 'Create an event — free',
      demo: 'See a sample gallery',
      trust: 'One payment from RM59. No subscription.',
      live: 'LIVE',
      photos: 'photos',
    },
    how: {
      eyebrow: 'How it works',
      title: 'Three steps. Nobody needs a tutorial.',
      steps: [
        { n: '01', title: 'Put the QR on the tables', body: 'Print our A5 or tent-card template and place one on every guest table and at the entrance.' },
        { n: '02', title: 'Guests scan & upload', body: 'Opens straight in the phone browser. Pick from the camera roll or shoot — 30 photos at a time.' },
        { n: '03', title: 'Live on the TV', body: 'Every photo shows up in the gallery and on the venue screen within seconds, with the name of who took it.' },
      ],
      phone: { title: 'Upload photos', sub: 'Pick from your camera roll or snap one now', uploading: 'Uploading…', done: 'Done! 12 photos are in the gallery' },
      tv: { scan: 'Scan to upload' },
    },
    features: {
      eyebrow: 'Features',
      title: 'Everything Wedibox has. In Ringgit, in your language.',
      items: [
        { title: 'Live gallery', body: 'Guest photos and videos land instantly. Originals kept; iPhone HEIC converted for you.' },
        { title: 'TV slideshow', body: 'One link for the venue laptop. New photos join the rotation, guest names included.' },
        { title: 'Digital invitation', body: 'Both families, programme, Waze & Google Maps, countdown, DuitNow gift QR. One link for everything.' },
        { title: 'RSVP & seating', body: 'Guests confirm and give pax, you arrange tables, guests find their own table number.' },
        { title: 'Written & voice wishes', body: 'Guests leave a message or record their voice right in the browser. No vintage phone rental.' },
        { title: 'Download everything', body: 'One zip, original quality, ordered by time. Hidden photos included, in their own folder.' },
        { title: 'Host controls', body: 'Hide, delete, or turn on approval mode so nothing shows until you have seen it.' },
        { title: 'Your own link', body: 'indahnya.my/aina-hakim. Short, easy to say, easy to print.' },
      ],
    },
    host: {
      eyebrow: 'For the host',
      title: 'A dashboard you can open from the dais.',
      body: 'All from your phone: how many photos are in, who has RSVPed, hide what does not belong, copy the TV link. Nothing is buried three menus deep.',
      stats: [
        { label: 'Photos & videos', value: '318', sub: 'in the gallery' },
        { label: 'Uploads used', value: '318', sub: 'unlimited' },
        { label: 'RSVP', value: '142', sub: '· 380 pax' },
        { label: 'Wishes', value: '27', sub: 'from guests' },
      ],
      recent: 'Latest photos',
      recentSub: 'Just in from guests',
      plan: 'Plan',
      planName: 'Indahnya Lengkap',
      planLine1: 'Uploads open for 341 more days',
      planLine2: 'Stored until 14 November 2028',
      actions: 'Do now',
      a1: 'Print table QR', a1s: 'A5, A4 or tent card',
      a2: 'Put the slideshow on the TV', a2s: 'Photos land live during the event',
      a3: 'Download everything (zip)', a3s: '318 files, original quality',
    },
    print: {
      eyebrow: 'For the tables',
      title: 'Print templates, ready with your QR and names.',
      body: 'Open, press Print. A5 for a table frame, A4 for the entrance stand, a fold-in-two tent card. In BM or English to match your guests.',
      items: ['A5 poster', 'A4 poster', 'Tent card'],
      headline: 'Snap & share our photos',
    },
    pricing: {
      eyebrow: 'Pricing',
      title: 'Pay once. For one event.',
      body: 'No subscription, no per-guest fee. Start free with every feature, upgrade when the gallery fills up.',
      plans: [
        { name: 'Free', price: 'RM0', tag: 'To try it', rows: ['50 uploads', '30-day upload window', '30-day storage', 'Every feature, slideshow & card included'], cta: 'Start free', hot: false },
        { name: 'Indahnya', price: 'RM59', tag: 'Most popular', rows: ['Unlimited uploads', '6-month upload window', '1-year storage', 'Your own link', '1 co-host'], cta: 'Choose Indahnya', hot: true },
        { name: 'Indahnya Lengkap', price: 'RM99', tag: 'For big events', rows: ['Unlimited uploads', '12-month upload window', '2-year storage', 'Your own link', '5 co-hosts', 'No Indahnya badge'], cta: 'Choose Lengkap', hot: false },
      ],
      note: 'Paid through Stripe — FPX, cards, GrabPay. Prices in Ringgit. Receipt by email.',
    },
    faq: {
      eyebrow: 'FAQ',
      title: 'What people ask.',
      items: [
        { q: 'Do guests need to install an app?', a: 'No. Scan the QR and the gallery opens in the phone browser. iPhone, Android, an aunty\'s old phone — all fine.' },
        { q: 'What if the venue has no signal?', a: 'Photos that did not make it retry when there is a connection. For the TV, use a phone hotspot — the slideshow keeps going with what it already has.' },
        { q: 'Can I filter out photos that do not belong?', a: 'Yes. Hide or delete from the dashboard, or turn on approval mode so photos only show after you have seen them.' },
        { q: 'How long are photos kept?', a: 'Free: 30 days. RM59: a year. RM99: two years. We email you 14 days before the end, and you can download everything any time.' },
        { q: 'Are videos supported?', a: 'Yes, up to 60 seconds each. We convert them to a format every phone plays, so an iPhone video works on Android too.' },
        { q: 'I already made an invitation elsewhere — can I use just the gallery?', a: 'Yes. There is a "photos only" QR and link that goes straight to the gallery — paste it into your e-invite.' },
        { q: 'Who makes Indahnya?', a: 'FF Dev Studio, a small studio in Malaysia. If something breaks, WhatsApp us — the person who built it answers.' },
      ],
    },
    cta: { title: 'Set up your event in two minutes.', body: 'Free to start. The QR is ready before you finish reading this.', button: 'Create an event free' },
    footer: { by: 'Made by', tagline: 'QR photo galleries for events, made for Malaysia.', links: { privacy: 'Privacy', terms: 'Terms', contact: 'Contact' } },
  },
} as const;

export type LandingLang = keyof typeof LANDING;
