/**
 * Landing copy, both languages, in one place. BM is the default and is
 * written the way people talk at a majlis; EN is for the SG/expat couple
 * and the venue manager. Keys follow the page from top to bottom.
 *
 * One label per intent: "Buat majlis percuma" is the only sign-up label on
 * the page, "Tengok contoh" the only sample link.
 */
export const LANDING = {
  ms: {
    nav: { how: 'Cara guna', kad: 'Kad', pricing: 'Harga', faq: 'Soalan', login: 'Log masuk', lang: 'EN', menu: 'Menu', close: 'Tutup' },
    cta: 'Buat majlis percuma',
    sample: 'Tengok contoh',
    hero: {
      eyebrow: 'Untuk kahwin, aqiqah, birthday dan majlis syarikat',
      h1a: 'Semua gambar majlis.',
      h1b: 'Satu QR.',
      sub: 'Tetamu scan, snap, upload. Tak payah app, tak payah login. Semua masuk satu galeri, live atas TV dewan.',
      card: 'Kongsi gambar majlis kami',
      wall: 'Aina & Hakim',
      wallSub: 'Galeri contoh, terus dari phone tetamu',
      feedUp: 'upload {n} gambar',
      feedNow: 'baru tadi',
      live: 'gambar',
    },
    nos: ['Download app', 'Buat akaun', 'Group WhatsApp "Gambar Kenduri"', 'Kejar sepupu minta gambar'],
    nosLead: 'Tak payah',
    story: 'Makcik snap dari meja empat. Kawan opis snap masa makan beradab. Sepupu snap dari belakang pelamin. Semuanya masuk satu tempat, kualiti asal, dengan nama siapa yang snap.',
    how: {
      title: 'Tiga langkah. Makcik pun boleh.',
      steps: [
        { title: 'Letak QR atas meja', body: 'Print poster A5, A4 atau kad meja. Nama korang dan QR dah siap tersusun.' },
        { title: 'Tetamu scan dan upload', body: 'Terus buka dalam browser phone. Pilih sampai 30 gambar sekali gus, atau snap terus.' },
        { title: 'Masuk galeri, naik TV', body: 'Dalam beberapa saat, setiap gambar ada dalam galeri dan atas skrin dewan.' },
      ],
      scan: 'indahnya.my/aina-hakim',
      open: 'Buka',
      uploading: 'Tengah upload',
      of: 'daripada',
      done: 'Siap! Dah masuk galeri',
      gallery: 'Gambar majlis',
      all: 'Semua',
      mine: 'Gambar saya',
      upload: 'Upload gambar',
    },
    live: {
      title: 'Lampu malap. Gambar naik.',
      body: 'Satu link untuk laptop dewan. Setiap gambar baru menyelit masuk slideshow, dengan nama tetamu.',
      tvScan: 'Scan untuk upload',
      photos: 'gambar',
      by: 'Dari',
      fresh: 'Baru masuk',
      tryTitle: 'Cuba sekarang.',
      tryBody: 'Scan QR atas skrin tu dengan phone korang, upload satu gambar, dan tengok dia naik kat sini. Hanya korang yang nampak, dan kami padam dalam sejam.',
      tryBodyPhone: 'Upload satu gambar dari phone ni dan tengok dia naik atas skrin. Hanya korang yang nampak, dan kami padam dalam sejam.',
      tryButton: 'Cuba upload gambar',
      tryDesk: 'atau pilih dari komputer',
      trySending: 'Tengah hantar',
      tryDone: 'Dah naik atas skrin',
      tryMore: 'Upload lagi',
      tryLimit: 'Cubaan ni enam gambar je. Buat majlis sendiri untuk tanpa had.',
      you: 'Korang',
    },
    kad: {
      title: 'Kad jemputan yang orang betul‑betul buka.',
      body: 'Lima template. Dua pihak, aturcara, Waze, countdown dan salam kaut DuitNow. Satu link untuk semua, dengan butang terus ke galeri.',
      pick: 'Pilih template',
      names: 'Cuba letak nama korang',
      a: 'Nama pertama',
      b: 'Nama kedua',
      phone: 'Ni kad sebenar. Scroll dalam phone tu.',
      perks: ['Waze & Google Maps', 'Countdown hari majlis', 'Aturcara', 'Salam kaut DuitNow', 'Lagu latar', 'Preview cantik dalam WhatsApp'],
    },
    guests: {
      title: 'Sebelum majlis, tetamu dah tahu semua.',
      rsvp: { title: 'RSVP', body: 'Hadir ke tak, berapa orang, pihak mana. Korang nampak jumlah terus.', coming: 'Hadir', pax: 'pax', sides: ['Lelaki', 'Perempuan', 'Rakan'], sample: 'Contoh: Aina & Hakim' },
      seat: { title: 'Cari nombor meja', body: 'Tetamu taip nama, terus dapat nombor meja. Cuba:', placeholder: 'Taip nama, contoh Ros', none: 'Tak jumpa nama tu dalam senarai contoh.', table: 'Meja', short: 'Taip sekurang-kurangnya 3 huruf' },
      wish: { title: 'Ucapan tulis atau suara', body: 'Tetamu tinggalkan ucapan, atau rakam suara terus dari browser.', record: 'Cuba rakam suara', stop: 'Berhenti', play: 'Main semula', again: 'Rakam lagi', note: 'Rakaman ni kekal dalam browser korang je.', denied: 'Mikrofon tak dapat dibuka. Bagi kebenaran dalam browser dulu.' },
    },
    host: {
      title: 'Dari atas pelamin pun boleh urus.',
      cards: [
        { title: 'Tapis sebelum naik', body: 'On approval mode, gambar hanya muncul lepas korang tengok. Sembunyi atau padam satu tap.' },
        { title: 'Download semua, kualiti asal', body: 'Satu zip, susun ikut masa. HEIC iPhone ditukar sendiri, video main kat semua phone.' },
        { title: 'Slideshow untuk TV dewan', body: 'Buka satu link kat laptop dewan. Gambar baru masuk sendiri, tak payah refresh.' },
        { title: 'QR siap print', body: 'Poster A5, A4 dan kad meja lipat dua, siap dengan tema kad korang. BM atau English, ikut tetamu.' },
      ],
      approve: 'Lulus', hide: 'Sembunyi', pending: 'Menunggu', zip: 'gambar-majlis-aina-hakim.zip', files: 'fail, kualiti asal', tv: 'Slideshow', print: ['Poster A5', 'Poster A4', 'Kad meja'],
    },
    pricing: {
      title: 'Bayar sekali. Untuk satu majlis.',
      body: 'Tak ada subscription, tak ada caj per tetamu. Semua ciri ada dalam pakej percuma. Upgrade bila gambar dah banyak.',
      once: 'sekali bayar',
      free: 'tak perlu kad bank',
      plans: [
        { name: 'Percuma', price: '0', tag: 'Untuk cuba', rows: ['50 upload', 'Upload sampai 30 hari selepas majlis', 'Simpan 30 hari selepas majlis', 'Semua ciri, termasuk kad dan slideshow'], hot: false },
        { name: 'Indahnya', price: '59', tag: 'Paling ramai pilih', rows: ['Upload tanpa had', 'Upload terbuka 6 bulan', 'Simpan setahun', 'Link sendiri, indahnya.my/nama-korang', '1 co-host'], hot: true },
        { name: 'Indahnya Lengkap', price: '99', tag: 'Untuk majlis besar', rows: ['Upload tanpa had', 'Upload terbuka 12 bulan', 'Simpan dua tahun', 'Link sendiri', '5 co-host', 'Tanpa badge Indahnya pada kad'], hot: false },
      ],
      choose: 'Pilih',
      note: 'Bayar melalui Stripe: FPX, kad atau GrabPay. Harga dalam Ringgit, resit ke email.',
    },
    faq: {
      title: 'Yang orang selalu tanya.',
      items: [
        { q: 'Tetamu kena download app ke?', a: 'Tak. Scan QR, browser phone terus buka galeri. iPhone, Android, phone lama makcik, semua jalan.' },
        { q: 'Kalau tak ada line kat dewan?', a: 'Gambar yang tak sempat upload akan sambung sendiri bila line kembali, asalkan page galeri masih terbuka. Untuk TV, guna hotspot phone. Slideshow tetap jalan dengan gambar yang dah ada.' },
        { q: 'Boleh tapis gambar yang tak sesuai?', a: 'Boleh. Sembunyi atau padam dari dashboard, atau on approval mode supaya gambar hanya naik selepas korang tengok.' },
        { q: 'Gambar disimpan berapa lama?', a: 'Percuma: 30 hari selepas majlis. RM59: setahun. RM99: dua tahun. Kiraan bermula dari hari majlis, bukan hari korang buat akaun. Kami email sebelum tamat, dan korang boleh download semua atau lanjutkan.' },
        { q: 'Video boleh?', a: 'Boleh, sampai 60 saat setiap satu. Kami tukar ke format yang main kat semua phone.' },
        { q: 'Kad jemputan dah buat kat tempat lain. Boleh guna galeri je?', a: 'Boleh. Ada QR dan link "gambar sahaja" yang terus masuk galeri. Paste dalam e-kad korang.' },
        { q: 'Siapa yang buat Indahnya?', a: 'FF Dev Studio, studio kecil di Malaysia. Kalau ada masalah, WhatsApp kami. Orang yang bina benda ni yang jawab.' },
      ],
    },
    final: { title: 'Majlis korang, siap dalam dua minit.', body: 'Percuma untuk mula. QR siap sebelum korang habis baca ayat ni.' },
    footer: { by: 'Dibuat oleh', tagline: 'Galeri gambar majlis dengan QR, untuk Malaysia.', links: { privacy: 'Privasi', terms: 'Terma', contact: 'Hubungi' } },
  },
  en: {
    nav: { how: 'How it works', kad: 'Invitation', pricing: 'Pricing', faq: 'FAQ', login: 'Sign in', lang: 'BM', menu: 'Menu', close: 'Close' },
    cta: 'Create your event free',
    sample: 'See a sample',
    hero: {
      eyebrow: 'For weddings, aqiqah, birthdays and company events',
      h1a: 'Every photo from the day.',
      h1b: 'One QR.',
      sub: 'Guests scan, snap and upload. No app, no sign-up. Everything lands in one gallery, live on the venue screen.',
      card: 'Share your photos of our day',
      wall: 'Aina & Hakim',
      wallSub: 'A sample gallery, straight from guests\' phones',
      feedUp: 'uploaded {n} photos',
      feedNow: 'just now',
      live: 'photos',
    },
    nos: ['Downloading an app', 'Making an account', 'A "Wedding Photos" WhatsApp group', 'Chasing cousins for photos'],
    nosLead: 'No more',
    story: 'An aunty snaps from table four. The office crowd snaps during the feast. A cousin snaps from behind the dais. All of it lands in one place, in full quality, with the name of whoever took it.',
    how: {
      title: 'Three steps. Every aunty can do it.',
      steps: [
        { title: 'Put the QR on the tables', body: 'Print an A5 or A4 poster, or a folded table card. Your names and the QR are already laid out.' },
        { title: 'Guests scan and upload', body: 'It opens right in the phone browser. Pick up to 30 photos at once, or shoot one now.' },
        { title: 'Into the gallery, onto the TV', body: 'Within seconds, every photo is in the gallery and on the venue screen.' },
      ],
      scan: 'indahnya.my/aina-hakim',
      open: 'Open',
      uploading: 'Uploading',
      of: 'of',
      done: 'Done! In the gallery',
      gallery: 'Event photos',
      all: 'All',
      mine: 'My photos',
      upload: 'Upload photos',
    },
    live: {
      title: 'Lights down. Photos up.',
      body: 'One link for the venue laptop. Every new photo slips into the slideshow, with the guest\'s name.',
      tvScan: 'Scan to upload',
      photos: 'photos',
      by: 'From',
      fresh: 'Just in',
      tryTitle: 'Try it now.',
      tryBody: 'Scan the QR on that screen with your phone, upload a photo, and watch it appear here. Only you can see it, and we delete it within the hour.',
      tryBodyPhone: 'Upload a photo from this phone and watch it land on the screen. Only you can see it, and we delete it within the hour.',
      tryButton: 'Try uploading a photo',
      tryDesk: 'or pick one from this computer',
      trySending: 'Sending',
      tryDone: 'It\'s on the screen',
      tryMore: 'Upload another',
      tryLimit: 'This demo takes six photos. Create your own event for unlimited.',
      you: 'You',
    },
    kad: {
      title: 'An invitation people actually open.',
      body: 'Five templates. Both families, the programme, Waze, a countdown and a DuitNow gift QR. One link for everything, with a button straight to the gallery.',
      pick: 'Pick a template',
      names: 'Try your own names',
      a: 'First name',
      b: 'Second name',
      phone: 'This is the real card. Scroll inside the phone.',
      perks: ['Waze & Google Maps', 'Countdown to the day', 'Programme', 'DuitNow gift QR', 'Background song', 'A proper WhatsApp preview'],
    },
    guests: {
      title: 'Before the day, guests know everything.',
      rsvp: { title: 'RSVP', body: 'Coming or not, how many, which side. You see the totals as they come in.', coming: 'Coming', pax: 'pax', sides: ['Groom', 'Bride', 'Friends'], sample: 'Sample: Aina & Hakim' },
      seat: { title: 'Find your table', body: 'Guests type their name and get their table number. Try:', placeholder: 'Type a name, e.g. Ros', none: 'No one by that name in the sample list.', table: 'Table', short: 'Type at least 3 letters' },
      wish: { title: 'Written and voice wishes', body: 'Guests leave a message, or record their voice right in the browser.', record: 'Try recording', stop: 'Stop', play: 'Play back', again: 'Record again', note: 'This recording stays in your browser.', denied: 'The microphone could not open. Allow it in your browser first.' },
    },
    host: {
      title: 'Run it from the dais.',
      cards: [
        { title: 'Check before it shows', body: 'Turn on approval mode and photos only appear after you have seen them. Hide or delete in one tap.' },
        { title: 'Download everything, full quality', body: 'One zip, in order of time. iPhone HEIC converted for you, videos that play on every phone.' },
        { title: 'A slideshow for the venue TV', body: 'Open one link on the venue laptop. New photos join on their own, no refreshing.' },
        { title: 'QR cards ready to print', body: 'A5 and A4 posters and a folded table card, dressed in your kad\'s template. In BM or English, for your guests.' },
      ],
      approve: 'Approve', hide: 'Hide', pending: 'Waiting', zip: 'event-photos-aina-hakim.zip', files: 'files, original quality', tv: 'Slideshow', print: ['A5 poster', 'A4 poster', 'Table card'],
    },
    pricing: {
      title: 'Pay once. For one event.',
      body: 'No subscription, no per-guest fee. Every feature is in the free plan. Upgrade when the photos pile up.',
      once: 'one-time',
      free: 'no card needed',
      plans: [
        { name: 'Free', price: '0', tag: 'To try it', rows: ['50 uploads', 'Uploads until 30 days after the event', 'Kept 30 days after the event', 'Every feature, card and slideshow included'], hot: false },
        { name: 'Indahnya', price: '59', tag: 'Most popular', rows: ['Unlimited uploads', 'Uploads open for 6 months', 'Kept for a year', 'Your own link, indahnya.my/your-names', '1 co-host'], hot: true },
        { name: 'Indahnya Lengkap', price: '99', tag: 'For big events', rows: ['Unlimited uploads', 'Uploads open for 12 months', 'Kept for two years', 'Your own link', '5 co-hosts', 'No Indahnya badge on the card'], hot: false },
      ],
      choose: 'Choose',
      note: 'Paid through Stripe: FPX, card or GrabPay. Prices in Ringgit, receipt by email.',
    },
    faq: {
      title: 'What people ask.',
      items: [
        { q: 'Do guests need to install an app?', a: 'No. Scan the QR and the gallery opens in the phone browser. iPhone, Android, an aunty\'s old phone, all fine.' },
        { q: 'What if the venue has no signal?', a: 'Photos that did not make it resume on their own when the connection comes back, as long as the gallery page stays open. For the TV, use a phone hotspot. The slideshow keeps going with what it has.' },
        { q: 'Can I filter out photos that do not belong?', a: 'Yes. Hide or delete from the dashboard, or turn on approval mode so photos only show after you have seen them.' },
        { q: 'How long are photos kept?', a: 'Free: 30 days after the event. RM59: a year. RM99: two years. The clock starts on the event day, not the day you sign up. We email you before the end, and you can download everything or extend.' },
        { q: 'Are videos supported?', a: 'Yes, up to 60 seconds each. We convert them to a format every phone plays.' },
        { q: 'I made my invitation elsewhere. Can I use just the gallery?', a: 'Yes. There is a "photos only" QR and link that goes straight to the gallery. Paste it into your e-invite.' },
        { q: 'Who makes Indahnya?', a: 'FF Dev Studio, a small studio in Malaysia. If something breaks, WhatsApp us. The person who built it answers.' },
      ],
    },
    final: { title: 'Your event, ready in two minutes.', body: 'Free to start. The QR is ready before you finish reading this.' },
    footer: { by: 'Made by', tagline: 'QR photo galleries for events, made for Malaysia.', links: { privacy: 'Privacy', terms: 'Terms', contact: 'Contact' } },
  },
} as const;

export type LandingLang = keyof typeof LANDING;
export type LandingCopy = (typeof LANDING)[LandingLang];

/** The landing's frames: Unsplash-licensed, Malaysian where we could find them. [width, height] of the 900px masters. */
export const PHOTOS: Record<string, [number, number]> = { g01: [900, 507], g02: [900, 1351], g03: [900, 600], g04: [900, 1351], g07: [900, 1350], g08: [900, 600], g09: [900, 1350], g10: [900, 1350], g11: [900, 600], g13: [900, 1350], g14: [900, 1350], g15: [900, 620], g17: [900, 1350], g18: [900, 600], g20: [900, 600], g21: [900, 1169], g22: [900, 1350] };
export const GUEST_NAMES = ['Makcik Ros', 'Aiman', 'Team Office', 'Kak Yati', 'Pak Long', 'Nadia & Irfan', 'Abang Faiz', 'Cousins', 'Uncle Lim', 'Syafiq', 'Auntie Mei', 'Hana'];
export const photo = (id: string, size: 's' | 'l' = 's') => (size === 's' ? `/landing/s/${id}.webp` : `/landing/${id}.jpg`);
