#!/usr/bin/env bash
#
# First-time provisioning of an Ubuntu 24.04 VPS for indahnya.my. Run as root
# ON THE SERVER (deploy/server.sh setup does it for you from the Mac):
#
#   scp deploy/setup-server.sh indahnya:/root/ && ssh indahnya bash /root/setup-server.sh
#
# Idempotent: safe to re-run. Writes no secrets except the database password it
# generates itself (into /etc/indahnya/env). Everything else comes from the Mac
# with deploy/env.sh push.
#
# Layout it creates:
#   /srv/indahnya/repo          a clone of the public repo; releases are cut from it
#   /srv/indahnya/releases/<sha> one build per deploy (deploy/deploy.sh)
#   /srv/indahnya/current       symlink to the live release
#   /srv/indahnya/shared/_nuxt  hashed assets of every release, so a tab opened
#                               before a deploy still finds its chunks
#   /etc/indahnya/env           runtime config (mode 600, owner indahnya)
#   /etc/ssl/cloudflare/        the Cloudflare origin certificate (deploy/cloudflare.sh)
set -euo pipefail
REPO="${REPO:-https://github.com/Aphrosidiac/Indahnya.git}"
APP=indahnya
HOME_DIR=/srv/indahnya
ENV_FILE=/etc/indahnya/env
export DEBIAN_FRONTEND=noninteractive

[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }
. /etc/os-release
[ "${VERSION_ID:-}" = "24.04" ] || echo "WARNING: written for Ubuntu 24.04, this is ${PRETTY_NAME:-unknown}" >&2

echo "== packages"
apt-get update -y
apt-get install -y curl git unzip ca-certificates nginx postgresql postgresql-contrib ufw \
  ffmpeg libheif-examples libheif-plugin-libde265 unattended-upgrades fail2ban
if ! command -v node >/dev/null || ! node -v | grep -qE '^v(22|24)\.'; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi
command -v pm2 >/dev/null || npm install -g pm2@latest
# AWS CLI v2 for the off-box database copies (Ubuntu 24.04 has no apt package)
if ! command -v aws >/dev/null; then
  t=$(mktemp -d); arch=$(uname -m)
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-${arch}.zip" -o "$t/aws.zip"
  unzip -q "$t/aws.zip" -d "$t" && "$t/aws/install" && rm -rf "$t"
fi

echo "== swap (a Nuxt build next to a running worker needs headroom)"
if ! swapon --show | grep -q . ; then
  fallocate -l 2G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  sysctl -w vm.swappiness=10 >/dev/null && echo 'vm.swappiness=10' > /etc/sysctl.d/99-indahnya.conf
fi

echo "== app user and folders"
id -u $APP >/dev/null 2>&1 || useradd -m -s /bin/bash $APP
mkdir -p $HOME_DIR/releases $HOME_DIR/shared/_nuxt /var/backups/indahnya /etc/indahnya /etc/ssl/cloudflare
touch /var/log/indahnya-backup.log
chown -R $APP:$APP $HOME_DIR /var/backups/indahnya /var/log/indahnya-backup.log
chmod 750 /etc/ssl/cloudflare
[ -d $HOME_DIR/repo/.git ] || sudo -u $APP git clone -q "$REPO" $HOME_DIR/repo

echo "== database"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$APP'" | grep -q 1; then
  DB_PW=$(openssl rand -hex 24)
  sudo -u postgres psql -qc "CREATE ROLE $APP LOGIN PASSWORD '$DB_PW'"
fi
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$APP'" | grep -q 1 || sudo -u postgres createdb -O $APP $APP

echo "== runtime config"
if [ ! -f $ENV_FILE ]; then
  [ -n "${DB_PW:-}" ] || { DB_PW=$(openssl rand -hex 24); sudo -u postgres psql -qc "ALTER ROLE $APP PASSWORD '$DB_PW'"; }
  cat > $ENV_FILE <<ENV
# Indahnya production config. Read by Node when a process STARTS
# (node --env-file); see .env.example and docs/deployment.md.
# Secrets arrive from the Mac with deploy/env.sh push; this file keeps any key
# the push does not carry.
DATABASE_URL=postgres://$APP:$DB_PW@127.0.0.1:5432/$APP
NUXT_PUBLIC_SITE_URL=https://indahnya.my
NUXT_S3_REGION=auto
NUXT_S3_BUCKET=indahnya-media
NUXT_S3_PRIVATE_BUCKET=indahnya-private
NUXT_S3_PUBLIC_BASE=https://media.indahnya.my
NUXT_SMTP_FROM=Indahnya <hello@indahnya.my>
BACKUP_S3_URI=s3://indahnya-backups
ENV
fi
chown $APP:$APP $ENV_FILE && chmod 600 $ENV_FILE

echo "== nginx"
# Cloudflare's addresses, so CF-Connecting-IP is trusted from them only; refreshed weekly
cat > /usr/local/sbin/indahnya-cf-ips <<'SH'
#!/usr/bin/env bash
set -euo pipefail
out=/etc/nginx/cloudflare-ips.conf; tmp=$(mktemp)
{ echo "# generated by indahnya-cf-ips from https://www.cloudflare.com/ips/"
  for v in 4 6; do curl -fsS "https://www.cloudflare.com/ips-v$v" | sed -E 's/^(.+)$/set_real_ip_from \1;/'; echo; done
  echo "real_ip_header CF-Connecting-IP;"; } > "$tmp"
grep -q set_real_ip_from "$tmp" || { echo "empty list, keeping the old one" >&2; exit 1; }
mv "$tmp" "$out" && chmod 644 "$out"
nginx -t -q 2>/dev/null && systemctl reload nginx || true
SH
chmod 755 /usr/local/sbin/indahnya-cf-ips
[ -f /etc/nginx/cloudflare-ips.conf ] || touch /etc/nginx/cloudflare-ips.conf  # nginx -t needs the file even if the first fetch fails
/usr/local/sbin/indahnya-cf-ips || echo "WARNING: could not fetch Cloudflare IPs; rerun /usr/local/sbin/indahnya-cf-ips" >&2
echo '17 4 * * 1 root /usr/local/sbin/indahnya-cf-ips >/dev/null 2>&1' > /etc/cron.d/indahnya-cf-ips
rm -f /etc/nginx/sites-enabled/default
# the vhost itself is installed by deploy/deploy.sh from the release (it needs the origin cert first)

echo "== firewall"
ufw allow OpenSSH >/dev/null; ufw allow 'Nginx Full' >/dev/null; ufw --force enable >/dev/null
systemctl enable --now fail2ban >/dev/null 2>&1 || true

echo "== PM2"
sudo -u $APP -H pm2 ping >/dev/null
sudo -u $APP -H pm2 describe pm2-logrotate >/dev/null 2>&1 || sudo -u $APP -H pm2 install pm2-logrotate >/dev/null
env PATH="$PATH" pm2 startup systemd -u $APP --hp /home/$APP >/dev/null

echo "== nightly backup (03:15 MYT is 19:15 UTC)"
echo "15 19 * * * $APP $HOME_DIR/current/scripts/backup-db.sh >> /var/log/indahnya-backup.log 2>&1" > /etc/cron.d/indahnya-backup

echo
echo "Provisioned. Versions: node $(node -v), $(psql --version | cut -d' ' -f1,3), $(nginx -v 2>&1 | cut -d/ -f2), ffmpeg $(ffmpeg -version | head -1 | cut -d' ' -f3)"
echo "Next, from the Mac: deploy/cloudflare.sh, deploy/env.sh push, deploy/deploy.sh --first"
